### ISSUE TITLE
app crash nach pausieren

### ISSUE THREAD

**Issue by eslafur** [eurofurence/ef-app_wp#1]
Nach verlassen der app ohne sie zu beenden (homescreen, Lockscreen, app wechseln) stürtzt die App beim fortsetzen ab.
V1.1.0.7

**Comment by Pinselohrkater** [comment]
Bekommst Du beim nächsten Start der App einen Crash Report, bzw. die Frage ob Du einen Crash-Dump senden möchtest?

**Comment by eslafur** [comment]
Es wird eine Meldung mit fehlercode ausgegeben, diese wird jedoch sofort geschlossen.
Den Crashreport habe ich einmal gesendet.

**Comment by eslafur** [comment]
![wp_ss_20160601_0008](https://cloud.githubusercontent.com/assets/16470950/15704478/3278e790-27eb-11e6-8825-fd441c845296.png)
Die Meldung im Moment des absturzes.

**Comment by Pinselohrkater** [comment]
Hab ihn gefunden, danke; der hilft mir weiter. Die App crasht übrigens nicht beim fortsetzen, sondern beim verlassen, bzw. on "suspension" wie ich gerade sehe. Windows 8.1 Mobile scheint da etwas vom Emulator-Verhalten abzuweichen (der Emulator verhält sich etwas speziell mit den ganzen Lifecycle-Events).

Sollte aber lösbar sein.

**Comment by eslafur** [comment]
Ich laufe unter 8.1
